replicaCount: 1
environment: prod

frontend:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 700m
      memory: 1Gi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    metric:
      resourceName: cpu
      targetType: Utilization
      averageUtilization: 70

backend:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 700m
      memory: 1Gi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    metric:
      resourceName: cpu
      targetType: Utilization
      averageUtilization: 70

db:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 700m
      memory: 1Gi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    metric:
      resourceName: cpu
      targetType: Utilization
      averageUtilization: 70
