replicaCount: 3
environment: prod

frontend:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 700m
      memory: 1Gi

backend:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 700m
      memory: 1Gi

db:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 700m
      memory: 1Gi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
