replicaCount: 1

imagePullPolicy: IfNotPresent
appName: khyaal


frontend:
  image: nginxdemos/hello
  port: 80
  resources: {}

backend:
  image: kennethreitz/httpbin
  port: 80
  resources: {}

db:
  image: postgres
  port: 3306
  username: postgres
  password: postgres
  resources: {}

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
