replicaCount: 1

imagePullPolicy: IfNotPresent
appName: khyaal


frontend:
  image: nginxdemos/hello
  port: 8080 
  resources: {}

backend:
  image: kennethreitz/httpbin
  port: 80
  resources: {}

postgres:
  image: mysql
  port: 3306
  mysqlRootPassword: mysql   # override per environment
  mysqlDatabase: mysql
  mysqlUser: mysql
  mysqlPassword: mysql
  resources: {}

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
