replicaCount: 1
environment: dev

frontend:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    metric:
      resourceName: cpu
      targetType: Utilization
      averageUtilization: 70

backend:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    metric:
      resourceName: cpu
      targetType: Utilization
      averageUtilization: 70

db:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    metric:
      resourceName: cpu
      targetType: Utilization
      averageUtilization: 70

