# FRONTEND 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-frontend-{{ .Values.environment }}
spec:
  # replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-frontend-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-frontend-{{ .Values.environment }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}

---

# BACKEND
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend-{{ .Values.environment }}
spec:
  # replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend-{{ .Values.environment }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/productstore
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
  

---

# DATABASE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-db-{{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}-db-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-db-{{ .Values.environment }}
    spec:
      containers:
        - name: db
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
              - name: MYSQL_ROOT_PASSWORD
                value: "{{ .Values.db.mysqlRootPassword }}"
              - name: MYSQL_DATABASE
                value: "{{ .Values.db.mysqlDatabase }}"
              - name: MYSQL_USER
                value: "{{ .Values.db.mysqlUser }}"
              - name: MYSQL_PASSWORD
                value: "{{ .Values.db.mysqlPassword }}"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          emptyDir: {}
