apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '<REPO_URL>'
    targetRevision: HEAD
    path: 'khyaal'
    helm:
      valueFiles:
        - values.yaml
        - dev/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true