apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: '<REPO_URL>'
    targetRevision: HEAD
    path: 'khyaal'
    helm:
      valueFiles:
        - values.yaml
        - prod/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
