apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: khyaal-dev-kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bhanubandi1999/khyaal-3-tier-app.git'
    targetRevision: HEAD
    path: kustomize/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
