apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: khyaal-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: khyaal-frontend
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: khyaal-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: khyaal-backend
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
